class Alquerque {
  constructor(state=null){if(state){Object.assign(this,state);this.board=state.board.slice();return;}this.board=Array(25).fill(null);this.currentPlayer='black';this.isGameOver=false;this.winner=null;this.setup();}
  setup(){for(let col=0;col<5;col++){this.board[col]='black';this.board[5+col]='black';this.board[15+col]='white';this.board[20+col]='white';}this.board[13]=this.board[14]='black';this.board[10]=this.board[11]='white';}
  adjacent(i){const r=Math.floor(i/5),c=i%5;const out=[];for(const[dr,dc]of[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]]){const nr=r+dr,nc=c+dc;if(nr>=0&&nr<5&&nc>=0&&nc<5)out.push(nr*5+nc);}return out;}
  captureMoves(from){const r=Math.floor(from/5),c=from%5,m=[];for(const mid of this.adjacent(from)){const mr=Math.floor(mid/5),mc=mid%5;const tr=mr+(mr-r),tc=mc+(mc-c),to=tr*5+tc;if(tr>=0&&tr<5&&tc>=0&&tc<5&&this.board[mid]&&this.board[mid]!==this.currentPlayer&&!this.board[to])m.push({to,captured:mid});}return m;}
  move(from,to){if(this.isGameOver||this.board[from]!==this.currentPlayer)return{success:false,error:'Invalid piece.'};const captures=this.captureMoves(from);if(captures.length){const jump=captures.find(m=>m.to===to);if(!jump)return{success:false,error:'A capture is mandatory.'};this.board[from]=null;this.board[jump.captured]=null;this.board[to]=this.currentPlayer;this.currentPlayer=this.currentPlayer==='black'?'white':'black';this.checkEnd();return{success:true,captured:true};}if(!this.board[to]&&!this.adjacent(from).includes(to))return{success:false,error:'Invalid move.'};this.board[from]=null;this.board[to]=this.currentPlayer;this.currentPlayer=this.currentPlayer==='black'?'white':'black';this.checkEnd();return{success:true};}
  checkEnd(){const opponent=this.currentPlayer==='black'?'white':'black';if(!this.board.includes(opponent)||!this.board.some((p,i)=>p===opponent&&this.captureMoves(i).length||p===opponent&&this.adjacent(i).some(to=>!this.board[to]))){this.isGameOver=true;this.winner=this.currentPlayer==='black'?'white':'black';}}
  toState(){return{board:this.board.slice(),currentPlayer:this.currentPlayer,isGameOver:this.isGameOver,winner:this.winner};}static fromState(s){return s?new Alquerque(s):new Alquerque();}
}
module.exports=Alquerque;
