class Dara {
  constructor(state=null){if(state){Object.assign(this,state);this.board=state.board.slice();return;}this.board=Array(30).fill(null);this.currentPlayer='black';this.phase='placement';this.placed={black:0,white:0};this.isGameOver=false;this.winner=null;}
  index(row,col){return row*6+col;} inBounds(r,c){return r>=0&&r<5&&c>=0&&c<6;}
  adjacent(i){const r=Math.floor(i/6),c=i%6;return [[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([row,col])=>this.inBounds(row,col)).map(([row,col])=>this.index(row,col));}
  linesAt(i){const r=Math.floor(i/6),c=i%6;const lines=[];if(c>=2)lines.push([i-2,i-1,i]);if(c>=1&&c<=4)lines.push([i-1,i,i+1]);if(c<=3)lines.push([i,i+1,i+2]);if(r>=2)lines.push([i-12,i-6,i]);if(r>=1&&r<=3)lines.push([i-6,i,i+6]);if(r<=2)lines.push([i,i+6,i+12]);return lines;}
  strictMill(i,color){return this.linesAt(i).some(line=>line.every(pos=>this.board[pos]===color)&&!this.linesAt(i).some(other=>other.length===4&&other.includes(i)&&other.every(pos=>this.board[pos]===color)));}
  move(from,to){if(this.isGameOver)return{success:false,error:'Game over.'};if(this.phase==='placement'){if(this.board[to]!==null||this.placed[this.currentPlayer]>=12)return{success:false,error:'Invalid placement.'};this.board[to]=this.currentPlayer;this.placed[this.currentPlayer]++;if(this.placed.black===12&&this.placed.white===12)this.phase='movement';this.currentPlayer=this.currentPlayer==='black'?'white':'black';return{success:true};}if(this.board[from]!==this.currentPlayer||this.board[to]!==null||!this.adjacent(from).includes(to))return{success:false,error:'Invalid move.'};this.board[from]=null;this.board[to]=this.currentPlayer;if(this.strictMill(to,this.currentPlayer)){const opponent=this.currentPlayer==='black'?'white':'black';const target=this.board.findIndex((piece,index)=>piece===opponent&&!this.strictMill(index,opponent));if(target>=0)this.board[target]=null;}if(this.board.filter(p=>p==='black').length<3||this.board.filter(p=>p==='white').length<3){this.isGameOver=true;this.winner=this.board.filter(p=>p==='black').length<3?'white':'black';}else this.currentPlayer=this.currentPlayer==='black'?'white':'black';return{success:true};}
  toState(){return{board:this.board.slice(),currentPlayer:this.currentPlayer,phase:this.phase,placed:{...this.placed},isGameOver:this.isGameOver,winner:this.winner};} static fromState(s){return s?new Dara(s):new Dara();}
}
module.exports=Dara;
