const EDGES = [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[10,11],[11,12],[1,6],[3,6],[5,6],[7,6],[9,6],[11,6],[0,6],[12,6]];
class Felli {
  constructor(state = null) { if (state) { Object.assign(this, state); return; } this.board = Array(13).fill(null); for (let index = 0; index < 6; index++) this.board[index] = { color: 'black', mullah: false }; for (let index = 7; index < 13; index++) this.board[index] = { color: 'white', mullah: false }; this.currentPlayer = 'black'; this.isGameOver = false; this.winner = null; }
  neighbors(index) { return EDGES.flatMap(([from,to]) => from === index ? [to] : to === index ? [from] : []); }
  jumps(from) { const piece = this.board[from]; const opponent = this.currentPlayer === 'black' ? 'white' : 'black'; const result = []; for (const middle of this.neighbors(from)) for (const to of this.neighbors(middle)) if (to !== from && this.board[middle]?.color === opponent && !this.board[to]) result.push({ to, over: middle }); return result; }
  moves(from) { const piece = this.board[from]; if (!piece || piece.color !== this.currentPlayer) return []; if (piece.mullah) return this.neighbors(from).filter((to) => !this.board[to]).map((to) => ({ to })); return this.neighbors(from).filter((to) => !this.board[to]).map((to) => ({ to })).concat(this.jumps(from)); }
  move(from, to) { const piece = this.board[from]; const capture = this.jumps(from).find((entry) => entry.to === to); const captures = this.board.flatMap((entry,index) => entry?.color === this.currentPlayer ? this.jumps(index).map((jump) => ({ from:index, ...jump })) : []); if (this.isGameOver || piece?.color !== this.currentPlayer || (captures.length ? !capture : !this.moves(from).some((entry) => entry.to === to))) return { success: false, error: 'Invalid Felli move.' }; this.board[to] = piece; this.board[from] = null; if (capture) this.board[capture.over] = null; if ((piece.color === 'black' && (to === 11 || to === 12)) || (piece.color === 'white' && (to === 0 || to === 1))) piece.mullah = true; const opponent = this.currentPlayer === 'black' ? 'white' : 'black'; const hasMove = this.board.some((entry,index) => entry?.color === opponent && this.movesFor(index, opponent).length); if (!this.board.some((entry) => entry?.color === opponent) || !hasMove) { this.isGameOver = true; this.winner = this.currentPlayer; } else this.currentPlayer = opponent; return { success: true, captured: Boolean(capture) }; }
  movesFor(index, color) { const previous = this.currentPlayer; this.currentPlayer = color; const result = this.moves(index); this.currentPlayer = previous; return result; }
  toState() { return { board: this.board.map((piece) => piece && { ...piece }), currentPlayer: this.currentPlayer, isGameOver: this.isGameOver, winner: this.winner }; }
  static fromState(state) { return state ? new Felli(state) : new Felli(); }
}
module.exports = Felli;
