const SIZE=8;
const RANK={pedine:1,dama:2,damone:3};
class ItalianDamone{
 constructor(state=null){if(state){Object.assign(this,state);return;}this.board=Array(64).fill(null);[0,1,2,3,4].forEach((col)=>{this.board[8+col]={color:'black',type:'pedine'};});this.board[7]={color:'black',type:'damone'};this.board[8+6]={color:'black',type:'dama'};this.board[8+7]={color:'black',type:'dama'};[56,57,58,59,60].forEach((index)=>{this.board[index]={color:'white',type:'pedine'};});this.board[63]={color:'white',type:'damone'};this.board[48]={color:'white',type:'dama'};this.board[49]={color:'white',type:'dama'};this.currentPlayer='black';this.isGameOver=false;this.winner=null;}
 row(i){return Math.floor(i/SIZE);}col(i){return i%SIZE;}
 directions(piece,capture=false){if(piece.type!=='pedine')return[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]];const forward=piece.color==='black'?1:-1;return capture?[[forward,-1],[forward,1],[-forward,-1],[-forward,1]]:[[forward,0],[0,-1],[0,1]];}
 captures(from){const piece=this.board[from];const result=[];const opponent=piece.color==='black'?'white':'black';for(const[dr,dc]of this.directions(piece,true)){const row=this.row(from)+dr,col=this.col(from)+dc,toRow=row+dr,toCol=col+dc;if(toRow>=0&&toRow<SIZE&&toCol>=0&&toCol<SIZE&&row>=0&&row<SIZE&&col>=0&&col<SIZE){const middle=row*SIZE+col,to=toRow*SIZE+toCol;if(this.board[middle]?.color===opponent&&RANK[this.board[middle].type]<=RANK[piece.type]&&!this.board[to])result.push({to,over:middle});}}return result;}
 moves(from){const piece=this.board[from];if(!piece||piece.color!==this.currentPlayer)return[];const captures=this.board.flatMap((entry,index)=>entry?.color===this.currentPlayer?this.captures(index).map((move)=>({from:index,...move})):[]);if(captures.length)return captures.filter((move)=>move.from===from);return this.directions(piece).map(([dr,dc])=>[this.row(from)+dr,this.col(from)+dc]).filter(([row,col])=>row>=0&&row<SIZE&&col>=0&&col<SIZE&&!this.board[row*SIZE+col]).map(([row,col])=>({from,to:row*SIZE+col}));}
 move(from,to){const candidate=this.moves(from).find((move)=>move.to===to);if(this.isGameOver||!candidate)return{success:false,error:'Invalid Italian Damone move.'};const piece=this.board[from];this.board[to]=piece;this.board[from]=null;if(candidate.over!==undefined)this.board[candidate.over]=null;if(piece.type==='pedine'&&((piece.color==='black'&&this.row(to)===7)||(piece.color==='white'&&this.row(to)===0)))piece.type='dama';else if(piece.type==='dama'&&((piece.color==='black'&&this.row(to)===7)||(piece.color==='white'&&this.row(to)===0)))piece.type='damone';const opponent=this.currentPlayer==='black'?'white':'black';if(!this.board.some((entry)=>entry?.color===opponent)||!this.board.some((entry,index)=>entry?.color===opponent&&this.movesFor(index,opponent).length)){this.isGameOver=true;this.winner=this.currentPlayer;}else this.currentPlayer=opponent;return{success:true,captured:candidate.over!==undefined};}
 movesFor(index,color){const previous=this.currentPlayer;this.currentPlayer=color;const result=this.moves(index);this.currentPlayer=previous;return result;}
 toState(){return{board:this.board.map((piece)=>piece&&{...piece}),currentPlayer:this.currentPlayer,isGameOver:this.isGameOver,winner:this.winner};}
 static fromState(state){return state?new ItalianDamone(state):new ItalianDamone();}
}
module.exports=ItalianDamone;
