const SIZE=8;
class Keny{
 constructor(state=null){if(state){Object.assign(this,state);return;}this.board=Array(64).fill(null);for(let row=1;row<=2;row++)for(let col=0;col<SIZE;col++)this.board[row*SIZE+col]={color:'black',pepper:false};for(let row=5;row<=6;row++)for(let col=0;col<SIZE;col++)this.board[row*SIZE+col]={color:'white',pepper:false};this.currentPlayer='black';this.noCaptureTurns=0;this.isGameOver=false;this.winner=null;}
 row(i){return Math.floor(i/SIZE);}col(i){return i%SIZE;}
 dirs(piece){return piece.pepper?[[-1,0],[1,0],[0,-1],[0,1]]:[[this.forward(piece),0],[0,-1],[0,1]];}
 forward(piece){return piece.color==='black'?1:-1;}
 captures(from){const piece=this.board[from],opponent=this.currentPlayer==='black'?'white':'black',result=[];for(const[dr,dc]of[[-1,0],[1,0],[0,-1],[0,1]]){let row=this.row(from)+dr,col=this.col(from)+dc;while(row>=0&&row<SIZE&&col>=0&&col<SIZE){const index=row*SIZE+col;if(!this.board[index]){if(piece.pepper){row+=dr;col+=dc;continue;}break;}if(this.board[index].color===piece.color){if(piece.pepper)break;row+=dr;col+=dc;continue;}if(this.board[index].color===opponent){let landRow=row+dr,landCol=col+dc;while(landRow>=0&&landRow<SIZE&&landCol>=0&&landCol<SIZE&&!this.board[landRow*SIZE+landCol]){result.push({to:landRow*SIZE+landCol,over:index});if(!piece.pepper)break;landRow+=dr;landCol+=dc;}break;}}}return result;}
 moves(from){const piece=this.board[from];if(!piece||piece.color!==this.currentPlayer)return[];const captures=this.board.flatMap((entry,index)=>entry?.color===this.currentPlayer?this.captures(index).map((move)=>({from:index,...move})):[]);if(captures.length)return captures.filter((move)=>move.from===from);const result=[];for(const[dr,dc]of this.dirs(piece)){let row=this.row(from)+dr,col=this.col(from)+dc;while(row>=0&&row<SIZE&&col>=0&&col<SIZE&&!this.board[row*SIZE+col]){result.push({from,to:row*SIZE+col});if(!piece.pepper&&!this.board[from+dr*SIZE+dc])break;row+=dr;col+=dc;}}return result;}
 move(from,to){const candidate=this.moves(from).find((move)=>move.to===to);if(this.isGameOver||!candidate)return{success:false,error:'Invalid Keny move.'};const piece=this.board[from];this.board[to]=piece;this.board[from]=null;if(candidate.over!==undefined){this.board[candidate.over]=null;this.noCaptureTurns=0;}else this.noCaptureTurns++;if(!piece.pepper&&((piece.color==='black'&&this.row(to)===7)||(piece.color==='white'&&this.row(to)===0)))piece.pepper=true;const opponent=this.currentPlayer==='black'?'white':'black';if(!this.board.some((entry)=>entry?.color===opponent)||!this.board.some((entry,index)=>entry?.color===opponent&&this.movesFor(index,opponent).length)){this.isGameOver=true;this.winner=this.currentPlayer;}else if(this.noCaptureTurns>=10){this.isGameOver=true;this.winner='draw';}else this.currentPlayer=opponent;return{success:true,captured:candidate.over!==undefined};}
 movesFor(index,color){const previous=this.currentPlayer;this.currentPlayer=color;const result=this.moves(index);this.currentPlayer=previous;return result;}
 toState(){return{board:this.board.map((piece)=>piece&&{...piece}),currentPlayer:this.currentPlayer,noCaptureTurns:this.noCaptureTurns,isGameOver:this.isGameOver,winner:this.winner};}
 static fromState(state){return state?new Keny(state):new Keny();}
}
module.exports=Keny;
