const SIZE=7;
class Kharbaga{
 constructor(state=null){if(state){Object.assign(this,state);return;}this.board=Array(49).fill(null);for(let index=0;index<20;index++)this.board[index]={color:'black',mullah:false};for(let index=29;index<49;index++)this.board[index]={color:'white',mullah:false};this.board[24]=null;this.currentPlayer='black';this.isGameOver=false;this.winner=null;}
 row(i){return Math.floor(i/SIZE);}col(i){return i%SIZE;}
 directions(piece,capture=false){if(piece.mullah)return[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]];const forward=piece.color==='black'?1:-1;return capture?[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]]:[[forward,0],[forward,-1],[forward,1]];}
 captures(from){const piece=this.board[from],opponent=this.currentPlayer==='black'?'white':'black',result=[];for(const[dr,dc]of this.directions(piece,true)){let row=this.row(from)+dr,col=this.col(from)+dc,found=false;while(row>=0&&row<SIZE&&col>=0&&col<SIZE){const index=row*SIZE+col;if(this.board[index]){if(found||this.board[index].color!==opponent)break;found=true;}else if(found)result.push({to:index,over:row*SIZE+col-dr*SIZE-dc});else if(!piece.mullah)break;row+=dr;col+=dc;}}return result;}
 moves(from){const piece=this.board[from];if(!piece||piece.color!==this.currentPlayer)return[];const captures=this.board.flatMap((entry,index)=>entry?.color===this.currentPlayer?this.captures(index).map((move)=>({from:index,...move})):[]);if(captures.length)return captures.filter((move)=>move.from===from);const result=[];for(const[dr,dc]of this.directions(piece)){let row=this.row(from)+dr,col=this.col(from)+dc;while(row>=0&&row<SIZE&&col>=0&&col<SIZE&&!this.board[row*SIZE+col]){result.push({from,to:row*SIZE+col});if(!piece.mullah)break;row+=dr;col+=dc;}}return result;}
 move(from,to){const candidate=this.moves(from).find((move)=>move.to===to);if(this.isGameOver||!candidate)return{success:false,error:'Invalid Kharbaga move.'};const piece=this.board[from];this.board[to]=piece;this.board[from]=null;if(candidate.over!==undefined)this.board[candidate.over]=null;if(!piece.mullah&&((piece.color==='black'&&this.row(to)===6)||(piece.color==='white'&&this.row(to)===0)))piece.mullah=true;const opponent=this.currentPlayer==='black'?'white':'black';if(!this.board.some((entry)=>entry?.color===opponent)){this.isGameOver=true;this.winner=this.currentPlayer;}else this.currentPlayer=opponent;return{success:true,captured:candidate.over!==undefined};}
 toState(){return{board:this.board.map((piece)=>piece&&{...piece}),currentPlayer:this.currentPlayer,isGameOver:this.isGameOver,winner:this.winner};}
 static fromState(state){return state?new Kharbaga(state):new Kharbaga();}
}
module.exports=Kharbaga;
