const SIZE=8;
class MakYek{
 constructor(state=null){if(state){Object.assign(this,state);return;}this.board=Array(64).fill(null);for(const row of[0,2])for(let col=0;col<SIZE;col++)this.board[row*SIZE+col]='black';for(const row of[5,7])for(let col=0;col<SIZE;col++)this.board[row*SIZE+col]='white';this.currentPlayer='black';this.isGameOver=false;this.winner=null;}
 row(i){return Math.floor(i/SIZE);}col(i){return i%SIZE;}
 lineClear(from,to){const dr=Math.sign(this.row(to)-this.row(from)),dc=Math.sign(this.col(to)-this.col(from));let row=this.row(from)+dr,col=this.col(from)+dc;while(row!==this.row(to)||col!==this.col(to)){if(this.board[row*SIZE+col])return false;row+=dr;col+=dc;}return true;}
 move(from,to){const piece=this.board[from],opponent=this.currentPlayer==='black'?'white':'black';if(this.isGameOver||piece!==this.currentPlayer||this.board[to]||((this.row(from)!==this.row(to)&&this.col(from)!==this.col(to))||!this.lineClear(from,to)))return{success:false,error:'Invalid Mak-yek move.'};this.board[to]=piece;this.board[from]=null;const captured=new Set();for(const[dr,dc]of[[0,1],[1,0]]){const row=this.row(to),col=this.col(to);for(const sign of[-1,1]){const nearRow=row+dr*sign,nearCol=col+dc*sign,farRow=row+dr*sign*2,farCol=col+dc*sign*2;if(nearRow>=0&&nearRow<SIZE&&nearCol>=0&&nearCol<SIZE&&farRow>=0&&farRow<SIZE&&farCol>=0&&farCol<SIZE){const near=nearRow*SIZE+nearCol,far=farRow*SIZE+farCol;if(this.board[near]===opponent&&this.board[far]===this.currentPlayer)captured.add(near);}}const beforeRow=row-dr,beforeCol=col-dc,afterRow=row+dr,afterCol=col+dc;if(beforeRow>=0&&beforeRow<SIZE&&beforeCol>=0&&beforeCol<SIZE&&afterRow>=0&&afterRow<SIZE&&afterCol>=0&&afterCol<SIZE){const before=beforeRow*SIZE+beforeCol,after=afterRow*SIZE+afterCol;if(this.board[before]===opponent&&this.board[after]===opponent)captured.add(before),captured.add(after);}}captured.forEach((index)=>{this.board[index]=null;});if(!this.board.includes(opponent)){this.isGameOver=true;this.winner=this.currentPlayer;}else this.currentPlayer=opponent;return{success:true,captured:captured.size};}
 toState(){return{board:this.board.slice(),currentPlayer:this.currentPlayer,isGameOver:this.isGameOver,winner:this.winner};}
 static fromState(state){return state?new MakYek(state):new MakYek();}
}
module.exports=MakYek;
