const SIZE=8;
class MingMang{
 constructor(state=null){if(state){Object.assign(this,state);return;}this.board=Array(64).fill(null);for(let row=0;row<2;row++)for(let col=1;col<8;col++)this.board[row*SIZE+col]='black';for(let row=6;row<8;row++)for(let col=0;col<7;col++)this.board[row*SIZE+col]='white';this.reserve={black:14,white:14};this.currentPlayer='black';this.history=[];this.isGameOver=false;this.winner=null;}
 row(i){return Math.floor(i/SIZE);}col(i){return i%SIZE;}
 lineClear(from,to){const dr=Math.sign(this.row(to)-this.row(from)),dc=Math.sign(this.col(to)-this.col(from));let row=this.row(from)+dr,col=this.col(from)+dc;while(row!==this.row(to)||col!==this.col(to)){if(this.board[row*SIZE+col])return false;row+=dr;col+=dc;}return true;}
 move(from,to){const piece=this.board[from],opponent=this.currentPlayer==='black'?'white':'black';if(this.isGameOver||piece!==this.currentPlayer||this.board[to]||(this.row(from)!==this.row(to)&&this.col(from)!==this.col(to))||!this.lineClear(from,to))return{success:false,error:'Invalid Ming mang move.'};const key=this.board.join(',')+`:${from}-${to}`;if(this.history.includes(key))return{success:false,error:'Repeated position is not allowed.'};this.board[to]=piece;this.board[from]=null;const captured=[];for(const[dr,dc]of[[0,1],[1,0]]){for(const sign of[-1,1]){const row=this.row(to)+dr*sign,col=this.col(to)+dc*sign,farRow=this.row(to)+dr*sign*2,farCol=this.col(to)+dc*sign*2;if(row>=0&&row<SIZE&&col>=0&&col<SIZE&&farRow>=0&&farRow<SIZE&&farCol>=0&&farCol<SIZE){const near=row*SIZE+col,far=farRow*SIZE+farCol;if(this.board[near]===opponent&&this.board[far]===this.currentPlayer)captured.push(near);}}}captured.forEach((index)=>{this.board[index]=this.currentPlayer;this.reserve[this.currentPlayer]--;});this.history.push(key);if(!this.board.includes(opponent)){this.isGameOver=true;this.winner=this.currentPlayer;}else this.currentPlayer=opponent;return{success:true,captured:captured.length};}
 toState(){return{board:this.board.slice(),reserve:{...this.reserve},currentPlayer:this.currentPlayer,history:this.history.slice(),isGameOver:this.isGameOver,winner:this.winner};}
 static fromState(state){return state?new MingMang(state):new MingMang();}
}
module.exports=MingMang;
