const SIZE = 5;
class Seega {
  constructor(state = null) { if (state) { Object.assign(this, state); return; } this.board = Array(25).fill(null); this.board[12] = 'blocked'; this.reserve = { black: 12, white: 12 }; this.currentPlayer = 'black'; this.phase = 'placement'; this.firstMove = true; this.isGameOver = false; this.winner = null; }
  row(index) { return Math.floor(index / SIZE); }
  col(index) { return index % SIZE; }
  neighbors(index) { const result=[]; for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]]){const row=this.row(index)+dr,col=this.col(index)+dc;if(row>=0&&row<SIZE&&col>=0&&col<SIZE)result.push({index:row*SIZE+col,dr,dc});} return result; }
  move(from,to) { const opponent=this.currentPlayer==='black'?'white':'black'; if(this.phase==='placement'){if(this.board[to]||this.reserve[this.currentPlayer]<=0)return{success:false,error:'Invalid Seega placement.'};this.board[to]=this.currentPlayer;this.reserve[this.currentPlayer]--;if(!this.reserve.black&&!this.reserve.white){this.phase='movement';this.currentPlayer='black';}else this.currentPlayer=opponent;return{success:true};} if(this.firstMove){if(this.currentPlayer!=='black'||from===undefined||this.board[from]!=='black'||to!==12)return{success:false,error:'Black must move to the center.'};this.board[to]='black';this.board[from]=null;this.firstMove=false;this.currentPlayer='white';return{success:true};} if(this.isGameOver||this.board[from]!==this.currentPlayer||this.board[to]||!this.neighbors(from).some((entry)=>entry.index===to))return{success:false,error:'Invalid Seega move.'};this.board[to]=this.currentPlayer;this.board[from]=null;for(const neighbor of this.neighbors(to)){const beyondRow=this.row(neighbor.index)+neighbor.dr,beyondCol=this.col(neighbor.index)+neighbor.dc;if(beyondRow>=0&&beyondRow<SIZE&&beyondCol>=0&&beyondCol<SIZE){const beyond=beyondRow*SIZE+beyondCol;if(this.board[neighbor.index]===opponent&&this.board[beyond]===this.currentPlayer)this.board[neighbor.index]=null;}}if(!this.board.includes(opponent)){this.isGameOver=true;this.winner=this.currentPlayer;}else this.currentPlayer=opponent;return{success:true};}
  toState(){return{board:this.board.slice(),reserve:{...this.reserve},currentPlayer:this.currentPlayer,phase:this.phase,firstMove:this.firstMove,isGameOver:this.isGameOver,winner:this.winner};}
  static fromState(state){return state?new Seega(state):new Seega();}
}
module.exports=Seega;
